version: "3.7"

services:
  db:
    image: postgres
    restart: always
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "123"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "ces_db"

  backend:
    image: ces:1.0.0
    restart: always
    container_name: backend
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/store_db